# Scraping
Scraping is the automated extraction of data from websites.

This bonus notebook Demonstrates scraping HTML tables using a Wikipedia table of G7 meetings as an example

# Data Scraping


For this example, we will scrape the list of G7 summits from Wikipedia, <a href="https://en.wikipedia.org/wiki/G7#List_of_summits">here</a>. It's a good target because it is:

- Available Online
- Not available as a clean download (Excel, CSV)

<img
height=500 src="https://raw.githubusercontent.com/jhellingsdata/RADataHub/main/misc/Masterclass/section%205/images/g7_wiki.png"> </img>

Before starting, we have to install and import the tool Pandas, which we'll use for scraping and data manipulation

In [ ]:
%pip install pandas

In [1]:
import pandas as pd # used for data scraping, and manipulation

First we define the URL of web-page we want to scrape from.

In [4]:
url = "Lebanese diaspora - Wikipedia.html" # The URL of the webpage
tables_from_web_page = pd.read_html(url) # Read the tables from the webpage into a list of DataFrames

In [29]:
def get_lower_bound(x):
  # Extract the first number from the estimate cell, splitting at "[" or " "

  if "according" in x:
    x= x.split(" ")[0]
    x = x.replace(",", "")
    x = int(x)
    return x

  if "[" in x:
    x= x.split("[")[0]
    x = x.replace(",", "")
    x = int(x)
    return x

In [30]:
x = "2,000,000 according to research conducted by I...	"
get_lower_bound(x)

2000000

In [33]:
df= tables_from_web_page[2]
df= df.head(15)
df['diaspora'] = df.Estimate.apply(get_lower_bound)
df = df[["Country" , "diaspora"]]
df.to_csv("leb_diaspora.csv")

/tmp/ipython-input-3120394985.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['diaspora'] = df.Estimate.apply(get_lower_bound)

pd.read_html returns a list of dataframes, one for each table on the webpage.
We can look through this list one by one by trying tables_from_webpage[0], tables_from_webpage[1], ...

In [ ]:
tables_from_webpage[2].head(10)

,#,Date,Host,Host leader,Location held,Notes
0,1st,15–17 November 1975,France,Valéry Giscard d'Estaing,"Château de Rambouillet, Yvelines",The first and last G6 summit.
1,2nd,27–28 June 1976,United States,Gerald R. Ford,"Dorado, Puerto Rico[74]","Also called ""Rambouillet II"". Canada joined th..."
2,3rd,7–8 May 1977,United Kingdom,James Callaghan,"London, England",The President of the European Commission was i...
3,4th,16–17 July 1978,West Germany,Helmut Schmidt,"Bonn, North Rhine-Westphalia",NaN
4,5th,28–29 June 1979,Japan,Masayoshi Ōhira,Tokyo,NaN
5,6th,22–23 June 1980,Italy,Francesco Cossiga,"Venice, Veneto",Prime Minister Ōhira died in office on 12 June...
6,7th,20–21 July 1981,Canada,Pierre E. Trudeau,"Montebello, Québec",NaN
7,8th,4–6 June 1982,France,François Mitterrand,"Versailles, Yvelines",NaN
8,9th,28–30 May 1983,United States,Ronald Reagan,"Williamsburg, Virginia",NaN
9,10th,7–9 June 1984,United Kingdom,Margaret Thatcher,"London, England",NaN

Trying tables_from_webpage[0], tables_from_webpage[1] and tables_from_webpage[2], we can see that tables_from_webpage[2] is the table we need.

Let's set the variable df equal to this table, for ease of use and take a look at the first few rows with df.head()

In [ ]:
df = tables_from_webpage[2]
df.head()

,#,Date,Host,Host leader,Location held,Notes
0,1st,15–17 November 1975,France,Valéry Giscard d'Estaing,"Château de Rambouillet, Yvelines",The first and last G6 summit.
1,2nd,27–28 June 1976,United States,Gerald R. Ford,"Dorado, Puerto Rico[74]","Also called ""Rambouillet II"". Canada joined th..."
2,3rd,7–8 May 1977,United Kingdom,James Callaghan,"London, England",The President of the European Commission was i...
3,4th,16–17 July 1978,West Germany,Helmut Schmidt,"Bonn, North Rhine-Westphalia",NaN
4,5th,28–29 June 1979,Japan,Masayoshi Ōhira,Tokyo,NaN

## Manipulating the Data

We can now manipulate the data. Let's try and make a chart of number of G7 meetings location.

First, let's group by the column 'Location held' and sort for just the most common places.

In [ ]:
df = tables_from_webpage[2]
df = df.groupby('Location held').aggregate({'Host': 'count'}) # Group the data by the 'Location held' column and count the number of occurrences
df = df.sort_values(by='Host', ascending=False) # Sort the data by the number of occurrences in descending order
df = df[df['Host'] > 1] # Keep only the rows where the number of occurrences is greater than 1
df = df.rename(columns={'Host': 'Count'}) # Rename the 'Host' column to 'Count'

df

                              Count
Location held
Tokyo                             3
London, England                   3
Bonn, North Rhine-Westphalia      2
Venice, Veneto                    2

## Uploading the Data

Now let's save our table to upload to GitHub and use in Vega-lite

In [ ]:
df.to_csv('g7_summits.csv') # Save the data to a CSV file

Next we have to upload our output (e.g. "g7_summits.csv") to GitHub. Got to your own repository and click 'Add file':

<img
style="max-height: 250px;
    width: auto;" src="https://raw.githubusercontent.com/jhellingsdata/RADataHub/main/misc/Masterclass/section%205/images/uploading_to_github.png"> </img>

Then find the file and click 'raw'

<img
style="max-height: 250px;
    width: auto;" src="https://raw.githubusercontent.com/jhellingsdata/RADataHub/main/misc/Masterclass/section%205/images/getting_raw.png"> </img>

and finally copy the url to use in Vega-lite:

<img
style="max-height: 250px;
    width: auto;" src="https://raw.githubusercontent.com/jhellingsdata/RADataHub/main/misc/Masterclass/section%205/images/getting_url.png"> </img>